DROP TABLE Property;
CREATE TABLE Property(
	ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
	PROPERTY_KEY VARCHAR(255), 
	PROPERTY_VALUE VARCHAR(255), 
	PROPERTY_DOC VARCHAR(255));
INSERT INTO Property (PROPERTY_KEY, PROPERTY_VALUE, PROPERTY_DOC) VALUES ('property.number','10','');
INSERT INTO Property (PROPERTY_KEY, PROPERTY_VALUE, PROPERTY_DOC) VALUES ('property.boolean','true','');
INSERT INTO Property (PROPERTY_KEY, PROPERTY_VALUE, PROPERTY_DOC) VALUES ('property.url','http://www.example.com','');